#This condenses model outputs from run_numerical_stability.R to a smaller file for plotting Figure S3
#This step is done to reduce file size by trimming the outputs to only what is used in plotting
#The "output_time_series_xxx" files are not included in the repository - they will need to be generated by the user with run_numerical_stability.R
#Only landscapes 0_0.1_4 and 0_0.8_5 are plotted in Figure S3...to completely replicate, only those landscapes need to be run in run_numerical_stability.R

rm(list=ls())

library(tidyverse)

landscape_time_series <- readRDS("data\\output_time_series_0_0.1_4.rds")

dV_index <- c(1, 12, 20, 28) #Corresponds to dV of 0.05, 2, 4, and 6
dV_list <- c(0.05, 2, 4, 6)

output_frame <- data.frame("unique_rep_id" = character(),
                           "dv" = numeric(),
                           "m_init" = numeric(),
                           "c_init" = numeric(),
                           "time" = integer(),
                           "mean_c" = numeric(),
                           "mean_m" = numeric())

for(i in 1:length(landscape_time_series)){
  for(j in 1:length(dV_index)){
    
    #Pulls out the time series for this set of conditions
    temp <- landscape_time_series[[i]][[dV_index[j]]]
    #Calculates the landscape mean macroalgae and coral values at each time step
    temp_M <- rowMeans(temp[,"Mi",])
    temp_C <- rowMeans(temp[,"C",])
    temp_frame <- data.frame("unique_rep_id" = rep("0_0.1_4", length(temp_M)),
                             "dv" = rep(dV_list[j], length(temp_M)),
                             "c_init" = rowMeans(temp[,"C",])[1],
                             "m_init" = rowMeans(temp[,"Mi",])[1],
                             "time" = 1:length(temp_M),
                             "mean_c" = rowMeans(temp[,"C",]),
                             "mean_m" = rowMeans(temp[,"Mi",])
    )
    
    #Appends time series to the output dataframe
    output_frame <- rbind(output_frame, temp_frame)
    
  }
}

######################
#SECOND EXAMPLE LANDSCAPE
#######################
landscape_time_series <- readRDS("data\\output_time_series_0_0.8_5.rds")

for(i in 1:length(landscape_time_series)){
  for(j in 1:length(dV_index)){
    
    #Pulls out the time series for this set of conditions
    temp <- landscape_time_series[[i]][[dV_index[j]]]
    #Calculates the landscape mean macroalgae and coral values at each time step
    temp_M <- rowMeans(temp[,"Mi",])
    temp_C <- rowMeans(temp[,"C",])
    temp_frame <- data.frame("unique_rep_id" = rep("0_0.8_5", length(temp_M)),
                             "dv" = rep(dV_list[j], length(temp_M)),
                             "c_init" = rowMeans(temp[,"C",])[1],
                             "m_init" = rowMeans(temp[,"Mi",])[1],
                             "time" = 1:length(temp_M),
                             "mean_c" = rowMeans(temp[,"C",]),
                             "mean_m" = rowMeans(temp[,"Mi",])
    )
    
    #Appends time series to the output dataframe
    output_frame <- rbind(output_frame, temp_frame)
    
  }
}

write_csv(output_frame, file = "data\\stability_figure_plotting.csv")